-- VIEW 
SELECT *
FROM  Upcoming__concerts;
SELECT *
FROM  Concert__location;
SELECT *
FROM  Merchandise__sold;
SELECT *
FROM   Featured__performer;
SELECT *
FROM  song_line__up;
SELECT *
FROM  Audience_;
